language: ruby
script: bundle exec jekyll build
branches:
  only:
    - master
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - cat $DEPLOY_KEY > .travis/deploy_key.pem
  - chmod 600 .travis/deploy_key.pem # this key should have push 
  - ssh-add .travis/deploy_key.pem
  - rm -rf _deploy
  - mkdir _deploy
  - cd _deploy
  - git clone https://github.com/opencompany/opencompany.github.io.git --branch=master .
  - git remote add deploy git@github.com:opencompany/opencompany.github.io.git
  - rsync -avzh ../_site/ ./
  - git add .
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email "$GIT_EMAIL"
  - git commit -m "New site version. Committed by Travis-CI."

#  - git config credential.helper "store --file=.git/credentials"
#  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git push deploy master
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.net##opencompany
    template:
    - '%{repository}#%{build_number} (%{branch}) %{message} %{build_url}'
